version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: meuat_postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - meuat_network

  seed:
    build:
      context: ./seed
      dockerfile: Dockerfile
    container_name: meuat_seed
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # (opcional) se quiser usar no script depois
      SHP_FILE: ${SHP_FILE}
    volumes:
      - ./seed/data:/seed/data:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - meuat_network
    restart: "no"
    command: ["python", "/seed/load_shapefiles.py"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meuat_api
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${API_HOST_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    networks:
      - meuat_network

volumes:
  postgres_data:

networks:
  meuat_network:
    driver: bridge
